<a href="https://colab.research.google.com/github/electrolabopen/archivoscsv/blob/master/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
 import torch

In [20]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [0]:
y = torch.tensor([
    [1, 2, 3],
    [8, 9, 7],
    [4, 5, 6]              

])
y

In [22]:
y = torch.tensor([
    [1, 2, 3],
    [8, 9, 7],
    [4, 5, 6]              

], dtype=torch.float)
y

tensor([[1., 2., 3.],
        [8., 9., 7.],
        [4., 5., 6.]])

In [23]:
torch.ones(1, 2, 3, dtype=torch.int)

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [0]:
torch.zeros(5, 3, 2, dtype=torch.float)

In [29]:
z= torch.rand(3, 4, 2, dtype= torch.float)
z
# imprime 3 conjuntos de 4 filas y 2 columnas

tensor([[[0.0773, 0.4433],
         [0.6026, 0.3568],
         [0.8004, 0.7003],
         [0.4951, 0.7654]],

        [[0.6037, 0.3964],
         [0.9258, 0.5508],
         [0.2418, 0.5450],
         [0.5111, 0.4097]],

        [[0.5328, 0.1035],
         [0.6828, 0.3008],
         [0.2001, 0.4856],
         [0.6099, 0.7536]]])

In [27]:
print(y)
y[0]
#imprimo los valores de y de la fila 0

tensor([[1., 2., 3.],
        [8., 9., 7.],
        [4., 5., 6.]])


tensor([1., 2., 3.])

In [28]:
y[:, 1]
# los elementos de la columna 1 los imprime

tensor([2., 9., 5.])

In [32]:
z[2, :, 0]
# imprimo el conjunto 2 y la columna 0

tensor([0.5328, 0.6828, 0.2001, 0.6099])

In [33]:
y.size()
#me dice el tamaño del  array 3 filas 3 columnas

torch.Size([3, 3])

In [34]:
y.size()[0]

3

In [35]:
t = torch.rand(3,3)
t

tensor([[0.5406, 0.2002, 0.4643],
        [0.4913, 0.6868, 0.1350],
        [0.0261, 0.8397, 0.8478]])

In [36]:
print(y)

tensor([[1., 2., 3.],
        [8., 9., 7.],
        [4., 5., 6.]])


In [37]:
y.reshape(1, 9)
#Los agrupa en una lista

tensor([[1., 2., 3., 8., 9., 7., 4., 5., 6.]])

In [39]:
torch.squeeze(y.reshape(1, 9))
#hace lo mismo

tensor([1., 2., 3., 8., 9., 7., 4., 5., 6.])

In [40]:
y.sum()
#suma todos los elementos de la lista

tensor(45.)

In [41]:
torch.max(y)
#me da el valor maximo de la lista

tensor(9.)

In [42]:
print(y)

tensor([[1., 2., 3.],
        [8., 9., 7.],
        [4., 5., 6.]])


In [44]:
values, indices = torch.max(y, 1)
print(values)
print(indices)
#Me imprime el valor maximo y el indice donde se encuentra

tensor([3., 9., 6.])
tensor([2, 1, 2])


In [50]:
y = [0, 0] == 1
y

False

In [60]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = torch.from_numpy(a)
b

tensor([[1, 2],
        [3, 4]])

In [62]:
a[0, 0] = 2
a
#modifico el array en la fila por el numero que quiero poner ejemplo 2

array([[2, 2],
       [3, 4]])

In [64]:
b

tensor([[2, 2],
        [3, 4]])